export const ADD_OPERATION = "ADD_OPERATION";
export const REMOVE_OPERATION = "REMOVE_OPERATION";
export const REMOVE_OPERATION_BY_ID = "REMOVE_OPERATION_BY_ID";
export const UPDATE_OPERATION_BY_ID = "UPDATE_OPERATION_BY_ID";
export const ADD_MANY_OPERATIONS = "ADD_MANY_OPERATIONS";
export const SET_OPERATIONS = "SET_OPERATIONS";